apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment # declarative deployment
metadata:
  name: nginx-deployment #deployment name
spec:
  selector:
    matchLabels:
      app: nginx #deployment app name
  replicas: 6 # Update the replicas from 2 to 6
  minReadySeconds: 10 # wait for 10 secs before the deploy of each pods
  strategy:
      type: rollingUpdate
      maxAvailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
